import { makeStyles } from "@mui/styles";
export const partnerStyle = makeStyles({
  container: {
    height: "100%",
    margin: "0 auto",
    width: "1200px",
  },
  partner: {
    paddingTop: "64px",
    backgroundColor: "var(--bg-gray)",
  },
  content: {
    display: "flex",
    justifyContent: "center",
    gap: "0 44px",
  },
  partnerInfor: {
    maxWidth: "670px",
  },
  partnerTitle: {
    fontStyle: "normal",
    fontWeight: "bold",
    fontSize: "32px",
    lineHeight: "36px",
    textAlign: "center",
    color: "var( --purple)",
    paddingBottom: "24px",
  },
  parnerImg: {
    margin: "0 auto",
    width: "480px",
    height: "360px",
    "& img": {
      height: "100%",
      objectFit: "cover",
    },
  },
  partnerDesc: {
    paddingTop: "24px",
    fontStyle: "normal",
    fontSize: "14px",
    lineHeight: "20px",
    fontWeight: 500,
    color: "var(--text-black)",
  },
  partnerList: {
    paddingTop: "24px",
    gap: "0  36px",
    display: "flex",
    flexDirection: "column",
  },
  partnerItem: {
    fontStyle: "normal",
    fontWeight: "bold",
    fontSize: "14px",
    lineHeight: "20px",
    color: "var(--text-black)",
    gridTemplateColumns: "repeat(2, 1fr)",
    display: "grid",
    gap: "0 36px",
    marginBottom: "16px",
  },
  partnerRegis: {
    maxWidth: "100%",
    boxShadow: "0px 6px 15px #DCD8EE",
    borderRadius: "24px",
    height: "max-content",
  },
  partnerRegisTitle: {
    fontFamily: "Quicksand",
    fontStyle: "normal",
    fontWeight: "bold",
    fontSize: "24px",
    lineHeight: "28px",
    maxWidth: "432px",
    textAlign: "center",
    color: "var( --purple)",
    margin: "36px 27px 32px 36px",
  },
  form: {
    padding: "0 36px",
  },
  wrapInput: {
    position: "relative",
    boxShadow: "inset 0px 2px 6px rgba(113, 97, 186, 0.2)",
    borderRadius: "18px",
    overflow: "hidden",
    width: "100%",
    marginBottom: "16px",
    "&:nth-child(6)": {
      marginBottom: "0",
    },
  },
  inputName: {
    width: "calc(100% - 64px)",
    padding: "8px",
    border: "0",
    margin: "0 36px 0 36px",
    backgroundColor: "transparent",
    fontStyle: "normal",
    fontWeight: 500,
    fontSize: "14px",
    lineHheight: "20px",
    color: "#A2A1AB",
    "&::placeholder": {
      color: "#A2A1AB",
    },
  },
  inputImgName: {
    width: "20px",
    height: "20px",
    position: "absolute",
    left: "16px",
    top: "50%",
    transform: "translateY(-50%)",
  },
  checkbox: {
    display: "flex",
    alignItems: "center",
    margin: "12px 0 0 -12px",
    "& span": {
      display: "flex",
    },
  },
  checkboxText: {
    fontStyle: "normal",
    fontWeight: 500,
    fontSize: "11px",
    lineHheight: "12px",
  },
  btnWrap: {
    display: "flex",
    justifyContent: "center",
    padding: "14px 0 36px 0",
  },
});
